FROM node:18-alpine

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json to install dependencies
COPY *.json ./

# Install dependencies
RUN npm install --frozen-lockfile

# Install tsc compiler and tsc-alias
RUN npm install typescript tsc-alias -g

# Copy the rest of the application code
COPY ./src ./src

# Build the TypeScript code
RUN npm run build

# Set the default command to run the compiled application
CMD ["node", "dist/bin/www.js"]
